<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-N62URNS" failures="1" tests="6" name="Default test" time="0.156" errors="0" timestamp="2025-09-10T17:51:27 IST">
  <testcase classname="com.ninza.crm.campaignstest.demo" name="add" time="0.025">
    <skipped/>
  </testcase> <!-- add -->
  <testcase classname="com.ninza.crm.campaignstest.demo" name="add" time="0.002">
    <skipped/>
  </testcase> <!-- add -->
  <testcase classname="com.ninza.crm.campaignstest.demo" name="add" time="0.007">
    <skipped/>
  </testcase> <!-- add -->
  <testcase classname="com.ninza.crm.campaignstest.demo" name="add" time="0.003">
    <skipped/>
  </testcase> <!-- add -->
  <testcase classname="com.ninza.crm.campaignstest.demo" name="add" time="0.002">
    <skipped/>
  </testcase> <!-- add -->
  <testcase classname="com.ninza.crm.campaignstest.demo" name="add" time="0.005">
    <failure type="junit.framework.ComparisonFailure" message="expected:&amp;lt;h[df]c&amp;gt; but was:&amp;lt;h[fd]c&amp;gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<h[df]c> but was:<h[fd]c>
at junit.framework.Assert.assertEquals(Assert.java:85)
at junit.framework.Assert.assertEquals(Assert.java:91)
at com.ninza.crm.campaignstest.demo.add(demo.java:11)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- add -->
</testsuite> <!-- Default test -->
